### PR TITLE
First pass at DSID -> Term mapping

### PR DESCRIPTION
**Pull request by dannylamb**
Resolves https://github.com/Islandora-CLAW/CLAW/issues/854

Depends on https://github.com/Islandora-CLAW/CLAW/issues/888 and https://github.com/Islandora-Devops/migrate_7x_claw/pull/8 (I'll make README updates once that lands so we don't have to merge documentation).

This PR adds its own tags migration to cover Media Use taxonomy terms not provided in core that are 7.x specific.

It also adds all of our Media Use tags to a static map in the `basic_image_media` migration, and references them via their external uri.

If you exeucte the tags migration to get all the taxonomy terms in, then you should be able to run the media migration, and all your media will be tagged appropriately!

screenshot from 2018-10-11 16-09-14

### CODE REVIEW

**Comment by mjordan** [comment]
Tested and works as described!

1. Checked out the `dannylamb:issue-854` branch.
1. Edited the .yml files to point to my Islandora 7.x server
1. Ran `drush -y fim islandora_migrate_7x_claw_feature`
1. Executed the "Islandora objects" migrations in the order listed in the Migrations UI.

**Review by whikloj — APPROVED** [review]
👍

**Comment by whikloj** [comment]
Are we good to go on this one?

**Comment by Natkeeran** [comment]
@dannylamb Does this need further testing?

**Comment by dannylamb** [comment]
@Natkeeran @whikloj Go for it.

**Pull request merged**
