### PR TITLE
Migration Improvements

### PR DESCRIPTION
**Pull request by dannylamb**
Resolves https://github.com/Islandora-CLAW/CLAW/issues/905

See README in this PR for installation and testing instructions.  There's a zip batch included if you need sample objects for 7.x

### CODE REVIEW

**Comment by mjordan** [comment]
@dannylamb testing this now and getting some strange results.

I ran the migration at the command line and it failed, giving this error:

```
[notice] Processed 204 items (198 created, 0 updated, 4 failed, 2 ignored) - done with 'islandora_basic_image_files'

In MigrateToolsCommands.php line 717:
                                                     
  islandora_basic_image_files Migration - 4 failed.  
```

Here's a screenshot of the "Messages" list for the files migration:

messages

The weird thing is that the failed object, `ir:1` is not in the Basic Images Collection. I'm not sure why it was migrated.                                                   

In case it helps, here's the RELS-EXT for 'ir:1':

```
<rdf:RDF xmlns:fedora="info:fedora/fedora-system:def/relations-external#" xmlns:fedora-model="info:fedora/fedora-system:def/model#" xmlns:islandora="http://islandora.ca/ontology/relsext#" xmlns:islandora-embargo="info:islandora/islandora-system:def/scholar#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="info:fedora/ir:1">
    <fedora:isMemberOfCollection rdf:resource="info:fedora/ir:citationCollection"></fedora:isMemberOfCollection>
    <fedora-model:hasModel rdf:resource="info:fedora/ir:citationCModel"></fedora-model:hasModel>
    <islandora-embargo:embargo-until rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-12-05T00:00:00Z</islandora-embargo:embargo-until>
    <islandora-embargo:embargo-expiry-notification-date rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-11-25T00:00:00Z</islandora-embargo:embargo-expiry-notification-date>
    <islandora:isViewableByUser>admin</islandora:isViewableByUser>
    <islandora:isViewableByUser>fedoraAdmin</islandora:isViewableByUser>
    <islandora:isViewableByRole>administrator</islandora:isViewableByRole>
  </rdf:Description>
</rdf:RDF>
```
As you can see, this object is embargoed, but I'm running the migration as fedoraAdmin, which should be able to view the object.

And I'm attaching my .yml files.

Also, looks like none of the media came over. I assume that's because the OBJ migration failed and it never got to the OBJ Media migration.

This 7.x repo is accessible to the outside world, let me know if you want access.




[marksyamlfiles.zip](https://github.com/Islandora-Devops/migrate_7x_claw/files/2577271/marksyamlfiles.zip)

**Comment by dannylamb** [comment]
This supercedes https://github.com/Islandora-Devops/migrate_7x_claw/pull/11

**Comment by dannylamb** [comment]
OK, I rolled in all the AUDIT changes into this, because I would've had to rewrite all the xpaths and I already did a ton of work converting that stuff to solr here.  Let me cook up better testing instructions.

**Comment by mjordan** [comment]
Will do.

**Comment by dannylamb** [comment]
e.g. update the readme

**Comment by dannylamb** [comment]
@mjordan Should work for you now.  I think it may even still be pointed at your Islandora 7.x :grin:  I'll need to change that too when updating the README.

**Comment by dannylamb** [comment]
@mjordan You'll have to pull down https://github.com/Islandora-CLAW/islandora/pull/105 and https://github.com/Islandora-CLAW/islandora_demo/pull/9, re-import those features, and then disable the derivative contexts so they don't fire during the migration.

Then you should get everything in your basic image collection, including the collection itself.  It'll even work with the test pdf you shoved in there.

**Comment by mjordan** [comment]
Which contexts are derivative contexts other than "Image Service File"?

**Comment by dannylamb** [comment]
@mjordan You should see two: `Image Service File` and `Image Original File`.

**Comment by mjordan** [comment]
@dannylamb islandora and isladora_demo are now on the `linked-agents` branch, as is migrate_7x_claw. All are up to date with your branches. Ran `drush cr`,`drush -y fim islandora` (no output), then `drush -y fim islandora_demo`, but am getting the following error when I run the last one:

```
In EntityType.php line 910:
                                                                                        
  Missing bundle entity, entity type taxonomy_vocabulary, entity id islandora_display.  
```
This happens regardless of whether the two contexts are disabled. Anything else I should be en/disabling or reloading before reloading the features?

**Comment by mjordan** [comment]
I'm flying out this afternoon, so might not get back to this until Saturday.

**Comment by dannylamb** [comment]
@mjordan No worries.  I think its' `drush -y fim islandora_core_feature`.  Maybe try that.

Either way, let me blow up my current environment and try to install it from scratch.  If I can I'll try to write it into a bash script.  That should save you some heartache.

**Comment by dannylamb** [comment]
Ok, so from a fresh box, you'll need set up your git:
- `git config --global user.email "joe@example.org"`
- `git config --global user.name "joe"`

Then use `composer` to get `migrate_7x_claw`:
- `cd /var/www/html/drupal/web`
- `composer require islandora/migrate_7x_claw`

Then pull down all three PRs.  Due to weird permissions issues I had to stash before `git pull`s.
- `cd /var/www/html/drupal/web/modules/contrib/migrate_7x_claw`
- `git checkout -b dannylamb-linked-agents master`
- `git stash`
- `git pull https://github.com/dannylamb/migrate_7x_claw.git linked-agents`
- `cd /var/www/html/drupal/web/modules/contrib/islandora`
- `git checkout -b dannylamb-linked-agents 8.x-1.x`
- `git stash`
- `git pull https://github.com/dannylamb/islandora.git linked-agents`
- `cd /var/www/html/drupal/web/modules/contrib/islandora_demo`
- `git checkout -b dannylamb-linked-agents 8.x-1.x`
- `git stash`
- `git pull https://github.com/dannylamb/islandora_demo.git linked-agents`

Then import the config
- `drush -y fim islandora_core_feature`
- `drush -y fim islandora_demo`
- `drush en islandora_migrate_7x_claw_feature`

I ran the migrations through drush with 
```
drush -y mim --group islandora_7x --update
```

I _did not_ disable any contexts, and although I got a bunch of these
```
 [error]  Error generating event: Could not locate source media
```
everything was fine.  Those should go away (and you'll have to disable the two contexts that generate derivatives) when https://github.com/Islandora-CLAW/islandora/pull/106 lands.

I got 22 items pulled over with 152 files and media.
screenshot from 2018-12-10 14-01-02
screenshot from 2018-12-10 14-01-24

**Comment by mjordan** [comment]
Spinning up a fresh box now.

**Comment by mjordan** [comment]
@dannylamb Yes! All worked as far as I can tell. Here's one of the resulting "Media" lists:

beauty

I also got a bunch of ` [error]  Error generating event: Could not locate source media` and the usual `fseek()` and `fclose()` warnings from FlysystemStreamWrapper. Also, the first two `git stash`es didn't have anything to stash.

Nice work!

**Comment by mjordan** [comment]
Should we be persisting the source object's PID during the migration, as per https://github.com/Islandora-CLAW/CLAW/issues/822?

**Comment by dannylamb** [comment]
@mjordan yeah i'd say so.  let me see if there's a good place to stuff it in the metadata profile.

**Comment by dannylamb** [comment]
@mjordan Also, i'll make a ticket for those `fseek` and `fclose` warnings.  We can squash those super easily and they're just noise.

**Comment by dannylamb** [comment]
`field_identifier` is lookin' pretty good!

**Comment by dannylamb** [comment]
@mjordan Ok, if you pull in these changes, you can get your PIDS as `field_identifier`.  You'll have to re-import the feature and then run the migration with `--update`.

```
vagrant@claw:/var/www/html/drupal/web/modules/contrib/migrate_7x_claw/modules/islandora_migrate_7x_claw_feature/config/install$ drush -y fim islandora_migrate_7x_claw_feature

 // Do you really want to import islandora_migrate_7x_claw_feature : migrate_plus.migration.islandora_objects?: yes.    

vagrant@claw:/var/www/html/drupal/web/modules/contrib/migrate_7x_claw/modules/islandora_migrate_7x_claw_feature/config/install$ drush -y mim islandora_objects --update
 [notice] Processed 22 items (0 created, 22 updated, 0 failed, 0 ignored) - done with 'islandora_objects'
```

screenshot from 2018-12-11 11-29-50

**Comment by mjordan** [comment]
Very cool will test. My only observation about using `field_identifier` is that it could also contain other identifiers (DOI, ISBN, blah blah blah). Should we use a more specific field?

**Comment by mjordan** [comment]
@dannylamb :+1: 

identifier

**Comment by mjordan** [comment]
For the record:

1. vagrant@claw:/var/www/html/drupal/web/modules/contrib/migrate_7x_claw$ `git pull https://github.com/dannylamb/migrate_7x_claw.git linked-agents`
1. `drush -y fim islandora_migrate_7x_claw_feature`
1. `drush -y mim --group islandora_7x --update`

**Comment by dannylamb** [comment]
@mjordan Yes, in its current state, the code will populate the field with both the PID and a MODS local identifier if present.  If we want to reserve one just for PIDs from 7.x and make it single valued, we can do that, np.  It would certainly make it easier to do `pathauto` tricks like `islandora/object/{pid}` if you're saddled with other identifiers.

**Comment by dannylamb** [comment]
@mjordan Ok, I updated the `islandora_demo` pull to include a PID field and storage.  I also updated this PR to migrate the PID field separately.

Pull down changes to both PRs, and then
- `drush -y fim islandora_demo`
- `drush -y fim islandora_migrate_7x_claw_feature`

And then `drush -y mim islandora_objects --update`

screenshot from 2018-12-11 13-57-07

**Comment by mjordan** [comment]
:+1: The new PID field is not showing up for me on the View tab, but it is present, and populated, in the Edit tab:

pid

I won't be at tomorrow's CLAW call, but it might be good to show this to the group to make sure everyone's OK with having a separate field.

Thanks, this is super impressive.

**Comment by dannylamb** [comment]
LOL it also swaps out Preservation Master for Original File, so there's a lot going on.  I'll be happy to demo it.

**Comment by dannylamb** [comment]
Well when you put it like that @ruebot I could at least squash that warning from flysystem with a `@` in the adapter.  Sometimes you forget how you've learned to ignore walls of text.

The ERROR isn't a big deal because you're getting all the datastreams over, but it shouldn't be happening.  It definitely comes down to how we've got an action and context configured.  I'd have to pull the thread a little further to pinpoint exactly where.

**Comment by dannylamb** [comment]
@ruebot @mjordan So that wall of warnings is actually handled if I pull in some upstream changes from the flysystem stream wrapper: https://github.com/twistor/flysystem-stream-wrapper/pull/9  I'll see what it takes to get those packages in properly.  I don't think it's pulled in by us directly, but through the flysystem module.

**Comment by whikloj** [comment]
So this works (sort of) and we can merge it in before it gets any bigger, but we need to 
1. clean up the errors produced while running it
1. Fix up the Migration UI look, it appears bizarrely
    image
1. Test it with some alternate content. I might be able to do that

**Comment by dannylamb** [comment]
@whikloj @ruebot I've asked @twistor to slice a new release of `flysystem-stream-wrapper` so we can get at a fix for those warnings from packagist without pulling from HEAD: https://github.com/twistor/flysystem-stream-wrapper/issues/11

I was getting the ERRORs other folks are seeing, but now can't seem to recreate them.  I'll have to blow away my environment and start from scratch.  I noticed that I hadn't disabled the `Image Preservation Master` context, and maybe it's acting up.  Once merged, new environments won't have it (they'll have a context for `Image Original File` instead).

As for those negative unprocessed numbers, I tried getting the same info from the command line to validate it and got
```bash
root@claw:/var/www/html/drupal/web/modules/contrib# drush migrate:status --group islandora_7x
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 [warning] array_diff(): Argument #1 is not an array Islandora.php:221
 ---------------------------------- ----------------------- -------- ------- ---------- ------------- --------------------- 
  Group                              Migration ID            Status   Total   Imported   Unprocessed   Last Imported        
 ---------------------------------- ----------------------- -------- ------- ---------- ------------- --------------------- 
  Islandora Objects (islandora_7x)   islandora_7x_tags       Idle     6       6          0             2018-12-20 13:07:49  
  Islandora Objects (islandora_7x)   islandora_audit_file    Idle     22      22         0             2018-12-20 13:08:01  
  Islandora Objects (islandora_7x)   islandora_person        Idle     22      0          22            2018-12-20 13:08:05  
  Islandora Objects (islandora_7x)   islandora_corporate     Idle     22      0          22            2018-12-20 13:08:08  
  Islandora Objects (islandora_7x)   islandora_subject       Idle     22      38         -16           2018-12-20 13:08:21  
  Islandora Objects (islandora_7x)   islandora_geographic    Idle     22      18         4             2018-12-20 13:08:33  
  Islandora Objects (islandora_7x)   islandora_objects       Idle     22      22         0             2018-12-20 13:08:42  
  Islandora Objects (islandora_7x)   islandora_audit_media   Idle     35      35         0             2018-12-20 13:08:59  
  Islandora Objects (islandora_7x)   islandora_files         Idle     0       152        -152          2018-12-20 13:10:23  
  Islandora Objects (islandora_7x)   islandora_media         Idle     0       152        -152          2018-12-20 13:11:58  
 ---------------------------------- ----------------------- -------- ------- ---------- ------------- --------------------- 

```
Those warnings point to https://github.com/dannylamb/migrate_7x_claw/blob/linked-agents/src/Plugin/migrate/source/Islandora.php#L221.  I'll revisit that logic.

**Comment by whikloj** [comment]
@dannylamb of course.

So the `islandora` source plugin needs an `islandora_type` which defines whether each row is an object or a set of datastreams.

[This](https://github.com/dannylamb/migrate_7x_claw/blob/linked-agents/src/Plugin/migrate/source/Islandora.php#L146) should probably default to `self::OBJECT_TYPE`.

But in the case of Media and Files we should define it as `islandora_type: datastreams` as it needs to count the datastreams. It does that by getting them from a Solr field defined in [`datastream_solr_field`](https://github.com/dannylamb/migrate_7x_claw/blob/linked-agents/src/Plugin/migrate/source/Islandora.php#L156).

Neither of those two options are defined, which is why it is failing to perform a count.

**Comment by whikloj** [comment]
So is everyone okay if I merge this and then we work to fix the underlying Islandora Source Plugin problems?

**Review by whikloj — APPROVED** [review]
As I said there are some underlying issues with the Islandora source plugin, but we can deal with those after this is in. 👍

**Pull request merged**
