### PR TITLE
Update migrate_plus.migration.islandora_files.yml

### PR DESCRIPTION
**Pull request by simonhm**
Hi Danny, 
There is one missing mime type for zip files: "application/x-zip"

# What does this Pull Request do?

Adding one missing mime type for zip files: "application/x-zip"

# What's new?
A in-depth description of the changes made by this PR. Technical details and
 possible side effects.

* Does this change require documentation to be updated? n
* Does this change add any new dependencies? n
* Does this change require any other modifications to be made to the repository
 (i.e. Regeneration activity, etc.)? n
* Could this change impact execution of existing code? n

### CODE REVIEW

**Comment by simonhm** [comment]
Screen Shot 2021-04-01 at 11 36 28 AM

**Comment by edlington** [comment]
There's still an error. Looks like there's an empty line in the file migrate_plus.migration.islandora_files.yml, on line 461. Here's the general area in the code where the empty line is. It occurs after the second fedoraAdmin in the auth: key
    plugin: download
    source:
      - '@remote_path'
      - '@local_path'
    guzzle_options:
      auth:
        - fedoraAdmin
        - fedoraAdmin
        
  uid: constants/creator_uid
destination:
  plugin: 'entity:file'
  default_bundle: image
migration_dependencies:
  required: { }
  optional: { }

Here's what drush is outputting: "Invalid data type in config migrate_plus.migration.islandora_files, found in file modules/contrib/migrate_7x_claw/modules/islandora_m  
  igrate_7x_claw_feature/config/install/migrate_plus.migration.islandora_files.yml: Unable to parse at line 461 (near "​"). "

**Comment by simonhm** [comment]
I don't see any empty line in this [migrate_plus.migration.islandora_files.yml ](https://github.com/Islandora-Devops/migrate_7x_claw/blob/main/modules/islandora_migrate_7x_claw_feature/config/install/migrate_plus.migration.islandora_files.yml)file. Also there isn't this lines: guzzle_options ...
The file migration (added the missing zip mime type) works well for me without errors. It seems like you're using/talking about this file in its old version.

**Comment by edlington** [comment]
@simonhm The migrate_plus.migration.islandora_files.yml you link to is the **old** version of the file, I think. On an isle_dc install I tried enabling migrate_7x_claw with the version of the migrate_plus.migration.islandora_files.yml you link to. It generated an error. See https://islandora.slack.com/archives/CM6F4C4VA/p1617225235217800?thread_ts=1617224520.217700&cid=CM6F4C4VA

I worked with Alexander O'Neill to fix that error. My comment above references the updated version of migrate_plus.migration.islandora_files.yml after working with Alexander to remove duplicate keys. If you composer require the migrate_7x_claw package and then go into its directory and git pull I believe the updated version of the migrate_plus.migration.islandora_files.yml file will be pulled into the install.

**Pull request closed without merging**
